package sendspin

import (
	"encoding/json"
	"os"
	"testing"
)

// The spec requires this filter exactly, so the port is held to the
// reference implementation's outputs, generated by testdata/gen_timefilter.py
// from aiosendspin 9.1.1. The input includes WiFi-shaped RTT spikes and a
// server clock step, so adaptive forgetting is exercised as well as the
// steady state.
func TestTimeFilterMatchesTheReferenceToTheMicrosecond(t *testing.T) {
	raw, err := os.ReadFile("testdata/timefilter_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vs []struct {
		M, E, T      int64
		Sync         bool
		Err          *int64
		Probes       []int64
		Server       []int64
		ServerProbes []int64 `json:"server_probes"`
		Client       []int64
	}
	if err := json.Unmarshal(raw, &vs); err != nil {
		t.Fatal(err)
	}
	if len(vs) < 200 {
		t.Fatalf("only %d vectors", len(vs))
	}
	f := newTimeFilter()
	for i, v := range vs {
		f.update(v.M, v.E, v.T)
		if got := f.synchronized(); got != v.Sync {
			t.Fatalf("step %d: synchronized=%v, reference %v", i, got, v.Sync)
		}
		if v.Err != nil && f.errorUs() != *v.Err {
			t.Fatalf("step %d: error %dus, reference %dus", i, f.errorUs(), *v.Err)
		}
		for k := range v.Probes {
			if got := f.serverTime(v.Probes[k]); got != v.Server[k] {
				t.Fatalf("step %d: serverTime(%d) = %d, reference %d", i, v.Probes[k], got, v.Server[k])
			}
			if got := f.clientTime(v.ServerProbes[k]); got != v.Client[k] {
				t.Fatalf("step %d: clientTime(%d) = %d, reference %d", i, v.ServerProbes[k], got, v.Client[k])
			}
		}
	}
}

// A measurement that does not move time forward is skipped, as the reference
// does: a backwards dt would run the prediction step in reverse.
func TestTimeFilterIgnoresNonMonotonicMeasurements(t *testing.T) {
	f := newTimeFilter()
	f.update(1000, 500, 10)
	f.update(9_999_999, 500, 10)
	if got := f.serverTime(10); got != 1010 {
		t.Errorf("a repeated timestamp moved the estimate: serverTime(10) = %d", got)
	}
}

func TestTimeSyncIntervalBacksOffAsTheEstimateTightens(t *testing.T) {
	f := newTimeFilter()
	if got := f.syncIntervalMs(); got != 200 {
		t.Errorf("unsynchronised: want 200ms, got %d", got)
	}
	f.update(1000, 400, 1)
	f.update(1000, 400, 2_000_000)
	if got := f.syncIntervalMs(); got != 3000 {
		t.Errorf("error %dus: want 3000ms, got %d", f.errorUs(), got)
	}
}

func TestSyncDiagWindow(t *testing.T) {
	f := newTimeFilter()
	f.update(100, 40, 1_000)
	f.update(130, 900, 2_000)
	f.update(90, 60, 3_000)
	f.update(500, 10, 3_000) // not after the last update: ignored, so not counted
	d := f.takeDiag()
	if d.N != 3 || d.DelayMinUs != 40 || d.DelayMaxUs != 900 || d.MeasMinUs != 90 || d.MeasMaxUs != 130 {
		t.Fatalf("diag = %+v", d)
	}
	if again := f.takeDiag(); again.N != 0 {
		t.Fatalf("window not reset: %+v", again)
	}
}
